"""Create all tables including speaker_events

Revision ID: c2bbe8f2bd29
Revises: bbfa55ebcab7
Create Date: 2025-06-03 18:38:13.284667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bbe8f2bd29'
down_revision: Union[str, None] = 'bbfa55ebcab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('session_uid', sa.String(), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=False),
    sa.Column('participant_id_meet', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('SPEAKER_START', 'SPEAKER_END', name='speakereventtype'), nullable=False),
    sa.Column('client_timestamp_ms', sa.BigInteger(), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('absolute_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_speaker_event_meeting_absolute_time', 'speaker_events', ['meeting_id', 'absolute_timestamp'], unique=False)
    op.create_index('ix_speaker_event_participant_meeting', 'speaker_events', ['meeting_id', 'participant_id_meet', 'absolute_timestamp'], unique=False)
    op.create_index('ix_speaker_event_session_time', 'speaker_events', ['session_uid', 'client_timestamp_ms'], unique=False)
    op.create_index(op.f('ix_speaker_events_absolute_timestamp'), 'speaker_events', ['absolute_timestamp'], unique=False)
    op.create_index(op.f('ix_speaker_events_event_type'), 'speaker_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_speaker_events_id'), 'speaker_events', ['id'], unique=False)
    op.create_index(op.f('ix_speaker_events_meeting_id'), 'speaker_events', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_speaker_events_participant_id_meet'), 'speaker_events', ['participant_id_meet'], unique=False)
    op.create_index(op.f('ix_speaker_events_session_uid'), 'speaker_events', ['session_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_events_session_uid'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_participant_id_meet'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_meeting_id'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_id'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_event_type'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_absolute_timestamp'), table_name='speaker_events')
    op.drop_index('ix_speaker_event_session_time', table_name='speaker_events')
    op.drop_index('ix_speaker_event_participant_meeting', table_name='speaker_events')
    op.drop_index('ix_speaker_event_meeting_absolute_time', table_name='speaker_events')
    op.drop_table('speaker_events')
    # ### end Alembic commands ###
